<?xml version="1.0"?>
<package format="3">
  <name>lidar_merge</name>
  <version>0.0.1</version>
  <description>PointCloud merger node for LiDARs</description>
  <maintainer email="jjh1@wise-automotive.com">wise</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>tf2</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
  
</package>